# Generated by Django 4.2 on 2023-05-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("icecream_tubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=8, unique=True),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scoops_requested", models.PositiveIntegerField()),
                (
                    "ice_cream_tub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icecream_tubs.icecreamtub",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
