# Generated by Django 4.2 on 2023-05-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="scoop_price",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="orders.order",
            ),
        ),
    ]
