# Generated by Django 4.2 on 2023-05-03 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_orderitem_scoop_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price_per_scoop",
        ),
    ]
