# Generated by Django 4.2 on 2023-05-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CHOCOLATE_ORANGE", "Chocolate Orange"),
                            ("MAPLE_SYRUP_WALNUT", "Maple Syrup Walnut"),
                            ("MINT_CHOCOLATE", "Mint Chocolate"),
                            (
                                "VANILLA_STRAWBERRY_CHOCOLATE",
                                "Vanilla Strawberry Chocolate",
                            ),
                            ("WHITE_CHOCOLATE_RASPBERRY", "White Chocolate Raspberry"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="flavor_photos"),
                ),
                ("recipe", models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="IceCreamTub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scoops_available", models.IntegerField(default=40)),
                (
                    "flavor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icecream_tubs.flavor",
                    ),
                ),
            ],
        ),
    ]
